### ISSUE TITLE
Responde-staking

### ISSUE THREAD

**Issue by huglif3** [huglif3/Responde#1]
**Idea:** 

There is no on chain way to verify attendance, nor is there a way to incentivize participants to attend after they RSVP.

**_Expected behavior_**

We need to build an RSVP DApp that allows you to purchase a ticket by staking Eth/Algo, and allowing you to withdraw them after you attend, and have been verified by the admin.

**Description**
What is the task?
Build an RSVP application, which allow you to
![Details page 1](https://user-images.githubusercontent.com/28884889/178113928-22d4b380-3b72-4fd3-857d-4677220e3a46.png)
- Create an event
- Have a back office/admin area for managing the event, 
- The Details necessary for the event should be:
- Title 
- Host Name / Links
- Type of Event
- Location
- Date & Time
![details page 2](https://user-images.githubusercontent.com/28884889/178113931-c7877596-0567-4340-b5cb-b61ddb10cbfd.png)
- Image
- Description
![ticketing information](https://user-images.githubusercontent.com/28884889/178113932-3e3e2fd4-f87b-4c46-86e6-103acbededd4.png)
- Ticket Tiers & ability to name them (i.e. VIP, General Admission)
- Ticket count per tier 
& Preview Page to look over the page before it is published.

A front facing area for users to purchase their tickets/RSVP by staking themselves.
User should be able to:

![interactions](https://user-images.githubusercontent.com/28884889/178113933-79d33249-4cf7-4849-94eb-edc338b15786.png)
- Connect wallet
- RSVP by staking x amount of $Eth
- Fill out a form with basic information: Name, email, twitter
- Unstake funds 24 hours before the event day
![Landing Page](https://user-images.githubusercontent.com/28884889/178113925-84fe4759-0297-477f-8283-bed4fd9a658c.png)

Working Document: https://docs.google.com/document/d/1p8FoMcGxH7bLK52GPGN05upRRj_C20Hrz-hwupRRJRg/edit?usp=sharing

**Comment by ArcAnya** [comment]
Split into issues #3 #4 and #5
